# Code generated by protoc-gen-twirp_ruby 1.0.0, DO NOT EDIT.
require 'twirp'
require_relative 'service_pb.rb'

module Courier
  class TweeterService < Twirp::Service
    package 'courier'
    service 'Tweeter'
    rpc :RegisterUser, RegisterUserRequest, User, :ruby_method => :register_user
    rpc :PostTweet, PostTweetRequest, Tweet, :ruby_method => :post_tweet
  end

  class TweeterClient < Twirp::Client
    client_for TweeterService
  end
end
